receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4317

processors:
  batch:
    timeout: 1s

exporters:
  loki:
    endpoint: http://loki:3100/loki/api/v1/push

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki]